version: "3"

services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "job"
      POSTGRES_PASSWORD: "dashboard"
      POSTGRES_DB: "job_dashboard"
    volumes:
      - "./data/postgres:/var/lib/postgresql/job-dashboard"
    ports:
      - "5432:5432"
  pgadmin:
    image: "dpage/pgadmin4:latest"
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
#   volumes:
#     - "./data/pgadmin:/var/lib/pgadmin"
    ports:
      - "8080:80"
